In [1]:
import csv
import os
import pandas as pd

In [4]:
csvdata = '/Users/philliphenson/Desktop/project1/Food_Access_USDA.csv'
df = pd.read_csv(csvdata)
df.shape

(948, 46)

In [5]:
df.head(5)

,OBJECTID,GEOID10,NAME10,PLNG_REGION,LILATracts_1And10,LILATracts_halfAnd10,LILATracts_1And20,LILATracts_Vehicle,Urban,Rural,...,lapop1share,lalowi1,lalowi1share,lakids1,lakids1share,laseniors1,laseniors1share,lahunv1,lahunv1share,GlobalID
0,1,13045910103,9101.03,ARC 20,0,0,0,0,0,1,...,0.830444,832.244207,0.165786,1212.092423,0.812939,388.429152,0.868969,30.598599,0.017656,{5550A054-FDCE-4733-8B0C-A1947228CE5D}
1,2,13045910104,9101.04,ARC 20,0,0,0,0,1,0,...,0.908498,2714.580415,0.292740,2531.804935,0.935281,613.913957,0.769316,105.395259,0.033133,{C6FF347E-7A0E-49CC-95F8-6442CAB49326}
2,3,13045910502,9105.02,ARC 20,1,1,1,1,1,0,...,0.677910,1634.143695,0.559638,394.285953,0.595598,108.874610,0.513559,141.638535,0.141497,{59E4487C-A509-45FF-95E5-D3C0BBE650BB}
3,4,13045910800,9108.00,ARC 20,0,0,0,0,0,1,...,1.000000,1557.335152,0.391881,958.000006,1.000000,491.000002,1.000000,41.470898,0.028405,{B14B7E5F-B673-439E-9C6E-638AD0B38A33}
4,5,13045910101,9101.01,ARC 20,1,1,1,1,1,0,...,0.247035,738.495538,0.124557,400.600253,0.237182,153.517815,0.282722,61.471188,0.027176,{C3D7DA7F-5468-4F0E-A705-CA99B9E57806}

In [6]:
print(df.columns)

Index(['OBJECTID', 'GEOID10', 'NAME10', 'PLNG_REGION', 'LILATracts_1And10',
       'LILATracts_halfAnd10', 'LILATracts_1And20', 'LILATracts_Vehicle',
       'Urban', 'Rural', 'LA1and10', 'LAhalfand10', 'LA1and20',
       'LATracts_half', 'LATracts1', 'LATracts10', 'LATracts20', 'HUNVFlag',
       'GroupQuartersFlag', 'OHU2010', 'NUMGQTRS', 'PCTGQTRS',
       'LowIncomeTracts', 'POP2010', 'UATYP10', 'lapophalf', 'lapophalfshare',
       'lalowihalf', 'lalowihalfshare', 'lakidshalf', 'lakidshalfshare',
       'laseniorshalf', 'laseniorshalfshare', 'lahunvhalf', 'lahunvhalfshare',
       'lapop1', 'lapop1share', 'lalowi1', 'lalowi1share', 'lakids1',
       'lakids1share', 'laseniors1', 'laseniors1share', 'lahunv1',
       'lahunv1share', 'GlobalID'],
      dtype='object')

In [10]:
# Create three DF's to store different columns
kids_df = df[{"GEOID10","NAME10","PLNG_REGION","Urban","lakidshalf","lakidshalfshare","lakids1","lakids1share","GlobalID"}]
kids_df

,lakids1,PLNG_REGION,lakids1share,GlobalID,lakidshalfshare,Urban,lakidshalf,GEOID10,NAME10
0,1212.092423,ARC 20,0.812939,{5550A054-FDCE-4733-8B0C-A1947228CE5D},0.892140,0,1330.181374,13045910103,9101.03
1,2531.804935,ARC 20,0.935281,{C6FF347E-7A0E-49CC-95F8-6442CAB49326},0.969294,1,2623.877557,13045910104,9101.04
2,394.285953,ARC 20,0.595598,{59E4487C-A509-45FF-95E5-D3C0BBE650BB},0.992790,1,657.226749,13045910502,9105.02
3,958.000006,ARC 20,1.000000,{B14B7E5F-B673-439E-9C6E-638AD0B38A33},1.000000,0,958.000006,13045910800,9108.00
4,400.600253,ARC 20,0.237182,{C3D7DA7F-5468-4F0E-A705-CA99B9E57806},0.744221,1,1256.990076,13045910101,9101.01
...,...,...,...,...,...,...,...,...,...
943,2519.536417,ARC 20,0.684471,{71987763-5C58-49E8-9DAE-B5F3E2E7E2DA},0.931305,1,3428.134246,13223120102,1201.02
944,2118.691044,ARC 20,0.762668,{CE73A80F-F658-48FD-91D0-A2B9D66ED1CC},0.917964,0,2550.102779,13223120103,1201.03
945,1449.743154,ARC 20,0.440785,{7CDED240-5D75-436B-BE4F-72E9E82FDD33},0.886995,1,2917.327602,13223120302,1203.02
946,1518.259609,ARC 20,0.737735,{36EAEB99-E656-4E24-97EC-2B747DA7D1BC},0.928530,1,1910.915240,13223120202,1202.02
947,5081.544245,ARC 20,0.993459,{A342945C-1EE3-47CE-974E-3EF37CF18862},1.000000,0,5114.999969,13223120400,1204.00

In [12]:
# Low income vs non low income

low_income_df = df[{"GEOID10","NAME10","PLNG_REGION","Urban","LowIncomeTracts","lalowihalf","lalowihalfshare","lalowi1","lalowi1share","GlobalID"}]
low_income_df

,PLNG_REGION,GlobalID,LowIncomeTracts,lalowihalf,lalowi1share,lalowihalfshare,lalowi1,Urban,GEOID10,NAME10
0,ARC 20,{5550A054-FDCE-4733-8B0C-A1947228CE5D},0,928.643255,0.165786,0.184989,832.244207,0,13045910103,9101.03
1,ARC 20,{C6FF347E-7A0E-49CC-95F8-6442CAB49326},0,2873.063683,0.292740,0.309831,2714.580415,1,13045910104,9101.04
2,ARC 20,{59E4487C-A509-45FF-95E5-D3C0BBE650BB},1,2388.115731,0.559638,0.817848,1634.143695,1,13045910502,9105.02
3,ARC 20,{B14B7E5F-B673-439E-9C6E-638AD0B38A33},1,1557.335152,0.391881,0.391881,1557.335152,0,13045910800,9108.00
4,ARC 20,{C3D7DA7F-5468-4F0E-A705-CA99B9E57806},1,2164.547997,0.124557,0.365078,738.495538,1,13045910101,9101.01
...,...,...,...,...,...,...,...,...,...,...
943,ARC 20,{71987763-5C58-49E8-9DAE-B5F3E2E7E2DA},0,1808.542071,0.114799,0.160460,1293.902235,1,13223120102,1201.02
944,ARC 20,{CE73A80F-F658-48FD-91D0-A2B9D66ED1CC},0,1373.688844,0.139289,0.160347,1193.293010,0,13223120103,1201.03
945,ARC 20,{7CDED240-5D75-436B-BE4F-72E9E82FDD33},0,4190.258936,0.173631,0.352241,2065.519935,1,13223120302,1203.02
946,ARC 20,{36EAEB99-E656-4E24-97EC-2B747DA7D1BC},0,2253.373996,0.228289,0.314849,1633.867000,1,13223120202,1202.02
947,ARC 20,{A342945C-1EE3-47CE-974E-3EF37CF18862},1,4737.150211,0.276499,0.278394,4704.904817,0,13223120400,1204.00