In [2]:
import csv
import os
import pandas as pd
import numpy as np

In [3]:
csvdata = '/Users/philliphenson/Desktop/project1/Food_Access_USDA.csv'
df = pd.read_csv(csvdata)
df.shape

(948, 46)

In [4]:
df.head(5)

,OBJECTID,GEOID10,NAME10,PLNG_REGION,LILATracts_1And10,LILATracts_halfAnd10,LILATracts_1And20,LILATracts_Vehicle,Urban,Rural,...,lapop1share,lalowi1,lalowi1share,lakids1,lakids1share,laseniors1,laseniors1share,lahunv1,lahunv1share,GlobalID
0,1,13045910103,9101.03,ARC 20,0,0,0,0,0,1,...,0.830444,832.244207,0.165786,1212.092423,0.812939,388.429152,0.868969,30.598599,0.017656,{5550A054-FDCE-4733-8B0C-A1947228CE5D}
1,2,13045910104,9101.04,ARC 20,0,0,0,0,1,0,...,0.908498,2714.580415,0.292740,2531.804935,0.935281,613.913957,0.769316,105.395259,0.033133,{C6FF347E-7A0E-49CC-95F8-6442CAB49326}
2,3,13045910502,9105.02,ARC 20,1,1,1,1,1,0,...,0.677910,1634.143695,0.559638,394.285953,0.595598,108.874610,0.513559,141.638535,0.141497,{59E4487C-A509-45FF-95E5-D3C0BBE650BB}
3,4,13045910800,9108.00,ARC 20,0,0,0,0,0,1,...,1.000000,1557.335152,0.391881,958.000006,1.000000,491.000002,1.000000,41.470898,0.028405,{B14B7E5F-B673-439E-9C6E-638AD0B38A33}
4,5,13045910101,9101.01,ARC 20,1,1,1,1,1,0,...,0.247035,738.495538,0.124557,400.600253,0.237182,153.517815,0.282722,61.471188,0.027176,{C3D7DA7F-5468-4F0E-A705-CA99B9E57806}

In [5]:
print(df.columns)

Index(['OBJECTID', 'GEOID10', 'NAME10', 'PLNG_REGION', 'LILATracts_1And10',
       'LILATracts_halfAnd10', 'LILATracts_1And20', 'LILATracts_Vehicle',
       'Urban', 'Rural', 'LA1and10', 'LAhalfand10', 'LA1and20',
       'LATracts_half', 'LATracts1', 'LATracts10', 'LATracts20', 'HUNVFlag',
       'GroupQuartersFlag', 'OHU2010', 'NUMGQTRS', 'PCTGQTRS',
       'LowIncomeTracts', 'POP2010', 'UATYP10', 'lapophalf', 'lapophalfshare',
       'lalowihalf', 'lalowihalfshare', 'lakidshalf', 'lakidshalfshare',
       'laseniorshalf', 'laseniorshalfshare', 'lahunvhalf', 'lahunvhalfshare',
       'lapop1', 'lapop1share', 'lalowi1', 'lalowi1share', 'lakids1',
       'lakids1share', 'laseniors1', 'laseniors1share', 'lahunv1',
       'lahunv1share', 'GlobalID'],
      dtype='object')

In [6]:
# Create three DF's to store different columns
kids_df = df[{"GEOID10","NAME10","PLNG_REGION","Urban","lakidshalf","lakidshalfshare","lakids1","lakids1share","GlobalID","lalowi1","lalowi1share","lapop1","lapop1share"}]
kids_df

,lakids1,PLNG_REGION,lakidshalf,GlobalID,lakidshalfshare,lalowi1share,GEOID10,lapop1,NAME10,lalowi1,lakids1share,Urban,lapop1share
0,1212.092423,ARC 20,1330.181374,{5550A054-FDCE-4733-8B0C-A1947228CE5D},0.892140,0.165786,13045910103,4168.828564,9101.03,832.244207,0.812939,0,0.830444
1,2531.804935,ARC 20,2623.877557,{C6FF347E-7A0E-49CC-95F8-6442CAB49326},0.969294,0.292740,13045910104,8424.506346,9101.04,2714.580415,0.935281,1,0.908498
2,394.285953,ARC 20,657.226749,{59E4487C-A509-45FF-95E5-D3C0BBE650BB},0.992790,0.559638,13045910502,1979.496369,9105.02,1634.143695,0.595598,1,0.677910
3,958.000006,ARC 20,958.000006,{B14B7E5F-B673-439E-9C6E-638AD0B38A33},1.000000,0.391881,13045910800,3974.000026,9108.00,1557.335152,1.000000,0,1.000000
4,400.600253,ARC 20,1256.990076,{C3D7DA7F-5468-4F0E-A705-CA99B9E57806},0.744221,0.124557,13045910101,1464.668253,9101.01,738.495538,0.237182,1,0.247035
...,...,...,...,...,...,...,...,...,...,...,...,...,...
943,2519.536417,ARC 20,3428.134246,{71987763-5C58-49E8-9DAE-B5F3E2E7E2DA},0.931305,0.114799,13223120102,7620.260307,1201.02,1293.902235,0.684471,1,0.676094
944,2118.691044,ARC 20,2550.102779,{CE73A80F-F658-48FD-91D0-A2B9D66ED1CC},0.917964,0.139289,13223120103,6703.747686,1201.03,1193.293010,0.762668,0,0.782508
945,1449.743154,ARC 20,2917.327602,{7CDED240-5D75-436B-BE4F-72E9E82FDD33},0.886995,0.173631,13223120302,5505.013546,1203.02,2065.519935,0.440785,1,0.462762
946,1518.259609,ARC 20,1910.915240,{36EAEB99-E656-4E24-97EC-2B747DA7D1BC},0.928530,0.228289,13223120202,5005.805781,1202.02,1633.867000,0.737735,1,0.699428
947,5081.544245,ARC 20,5114.999969,{A342945C-1EE3-47CE-974E-3EF37CF18862},1.000000,0.276499,13223120400,16900.097472,1204.00,4704.904817,0.993459,0,0.993189

In [7]:
# Low income vs non low income

low_income_df = df[{"GEOID10","NAME10","PLNG_REGION","Urban","LowIncomeTracts","lalowihalf","lalowihalfshare","lalowi1","lalowi1share","GlobalID","lapop1","POP2010","lapophalf","lapophalfshare","lapop1","lapop1share"}]
low_income_df

,PLNG_REGION,GlobalID,lapophalfshare,lalowi1share,GEOID10,lapop1,NAME10,lalowihalfshare,lalowihalf,lalowi1,POP2010,Urban,lapophalf,lapop1share,LowIncomeTracts
0,ARC 20,{5550A054-FDCE-4733-8B0C-A1947228CE5D},0.908377,0.165786,13045910103,4168.828564,9101.03,0.184989,928.643255,832.244207,5020,0,4560.050754,0.830444,0
1,ARC 20,{C6FF347E-7A0E-49CC-95F8-6442CAB49326},0.962295,0.292740,13045910104,8424.506346,9101.04,0.309831,2873.063683,2714.580415,9273,1,8923.358003,0.908498,0
2,ARC 20,{59E4487C-A509-45FF-95E5-D3C0BBE650BB},0.994330,0.559638,13045910502,1979.496369,9105.02,0.817848,2388.115731,1634.143695,2920,1,2903.442168,0.677910,1
3,ARC 20,{B14B7E5F-B673-439E-9C6E-638AD0B38A33},1.000000,0.391881,13045910800,3974.000026,9108.00,0.391881,1557.335152,1557.335152,3974,0,3974.000026,1.000000,1
4,ARC 20,{C3D7DA7F-5468-4F0E-A705-CA99B9E57806},0.762267,0.124557,13045910101,1464.668253,9101.01,0.365078,2164.547997,738.495538,5929,1,4519.483605,0.247035,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
943,ARC 20,{71987763-5C58-49E8-9DAE-B5F3E2E7E2DA},0.929397,0.114799,13223120102,7620.260307,1201.02,0.160460,1808.542071,1293.902235,11271,1,10475.236037,0.676094,0
944,ARC 20,{CE73A80F-F658-48FD-91D0-A2B9D66ED1CC},0.923887,0.139289,13223120103,6703.747686,1201.03,0.160347,1373.688844,1193.293010,8567,0,7914.940175,0.782508,0
945,ARC 20,{7CDED240-5D75-436B-BE4F-72E9E82FDD33},0.890380,0.173631,13223120302,5505.013546,1203.02,0.352241,4190.258936,2065.519935,11896,1,10591.961287,0.462762,0
946,ARC 20,{36EAEB99-E656-4E24-97EC-2B747DA7D1BC},0.915706,0.228289,13223120202,5005.805781,1202.02,0.314849,2253.373996,1633.867000,7157,1,6553.704673,0.699428,0
947,ARC 20,{A342945C-1EE3-47CE-974E-3EF37CF18862},1.000000,0.276499,13223120400,16900.097472,1204.00,0.278394,4737.150211,4704.904817,17016,0,17015.999911,0.993189,1

In [8]:
# Rename columns
low_income_df=low_income_df.rename(columns={"PLNG_REGION": "Metro_Atlanta", "GlobalID": "Global_ID","LowIncomeTracts": "Income_Level", "lalowihalf": "LowAcces_LowIncome05miles", "lalowi1share": "LowAccess_LowIncome1milePRCT", "lalowihalfshare": "LowAccess_LowIncome05milesPRCT", "lalowi1": "LowAccess_LowIncome1mile", "GEOID10": "Geo_ID", "NAME10": "Name"})
low_income_df

,Metro_Atlanta,Global_ID,lapophalfshare,LowAccess_LowIncome1milePRCT,Geo_ID,lapop1,Name,LowAccess_LowIncome05milesPRCT,LowAcces_LowIncome05miles,LowAccess_LowIncome1mile,POP2010,Urban,lapophalf,lapop1share,Income_Level
0,ARC 20,{5550A054-FDCE-4733-8B0C-A1947228CE5D},0.908377,0.165786,13045910103,4168.828564,9101.03,0.184989,928.643255,832.244207,5020,0,4560.050754,0.830444,0
1,ARC 20,{C6FF347E-7A0E-49CC-95F8-6442CAB49326},0.962295,0.292740,13045910104,8424.506346,9101.04,0.309831,2873.063683,2714.580415,9273,1,8923.358003,0.908498,0
2,ARC 20,{59E4487C-A509-45FF-95E5-D3C0BBE650BB},0.994330,0.559638,13045910502,1979.496369,9105.02,0.817848,2388.115731,1634.143695,2920,1,2903.442168,0.677910,1
3,ARC 20,{B14B7E5F-B673-439E-9C6E-638AD0B38A33},1.000000,0.391881,13045910800,3974.000026,9108.00,0.391881,1557.335152,1557.335152,3974,0,3974.000026,1.000000,1
4,ARC 20,{C3D7DA7F-5468-4F0E-A705-CA99B9E57806},0.762267,0.124557,13045910101,1464.668253,9101.01,0.365078,2164.547997,738.495538,5929,1,4519.483605,0.247035,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
943,ARC 20,{71987763-5C58-49E8-9DAE-B5F3E2E7E2DA},0.929397,0.114799,13223120102,7620.260307,1201.02,0.160460,1808.542071,1293.902235,11271,1,10475.236037,0.676094,0
944,ARC 20,{CE73A80F-F658-48FD-91D0-A2B9D66ED1CC},0.923887,0.139289,13223120103,6703.747686,1201.03,0.160347,1373.688844,1193.293010,8567,0,7914.940175,0.782508,0
945,ARC 20,{7CDED240-5D75-436B-BE4F-72E9E82FDD33},0.890380,0.173631,13223120302,5505.013546,1203.02,0.352241,4190.258936,2065.519935,11896,1,10591.961287,0.462762,0
946,ARC 20,{36EAEB99-E656-4E24-97EC-2B747DA7D1BC},0.915706,0.228289,13223120202,5005.805781,1202.02,0.314849,2253.373996,1633.867000,7157,1,6553.704673,0.699428,0
947,ARC 20,{A342945C-1EE3-47CE-974E-3EF37CF18862},1.000000,0.276499,13223120400,16900.097472,1204.00,0.278394,4737.150211,4704.904817,17016,0,17015.999911,0.993189,1

In [9]:
# Drop stuff from dataframe
# This drops all 0 values from "Urban"
low_income_df = low_income_df[low_income_df.Urban != 0]
low_income_df
# Change values in dataframe
# for col in low_income_df.columns():
# low_income_df.loc[low_income_df["Income_Level"] == '0', "Income_Level"] = "Not Low Income"
# low_income_df.loc[low_income_df["Income_Level"] == '1', "Income_Level"] = "Low Income" 

# low_income_df.Income_Level = low_income_df.Income_Level.map({ 0 : "Not Low Income", 1 : "Low Income"})

low_income_df.replace({'Income_Level':{0:"Not Low Income",1:"Low Income"}},inplace=True)
low_income_df

/Users/philliphenson/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:1676: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(ilocs[0], value, pi)

,Metro_Atlanta,Global_ID,lapophalfshare,LowAccess_LowIncome1milePRCT,Geo_ID,lapop1,Name,LowAccess_LowIncome05milesPRCT,LowAcces_LowIncome05miles,LowAccess_LowIncome1mile,POP2010,Urban,lapophalf,lapop1share,Income_Level
1,ARC 20,{C6FF347E-7A0E-49CC-95F8-6442CAB49326},0.962295,0.292740,13045910104,8424.506346,9101.04,0.309831,2873.063683,2714.580415,9273,1,8923.358003,0.908498,Not Low Income
2,ARC 20,{59E4487C-A509-45FF-95E5-D3C0BBE650BB},0.994330,0.559638,13045910502,1979.496369,9105.02,0.817848,2388.115731,1634.143695,2920,1,2903.442168,0.677910,Low Income
4,ARC 20,{C3D7DA7F-5468-4F0E-A705-CA99B9E57806},0.762267,0.124557,13045910101,1464.668253,9101.01,0.365078,2164.547997,738.495538,5929,1,4519.483605,0.247035,Low Income
5,ARC 20,{68A7D1D7-2258-4893-A214-168B6A59D4C3},0.943188,0.250140,13045910200,9346.658357,9102.00,0.296743,3480.197243,2933.637950,11728,1,11061.713867,0.796952,Not Low Income
8,ARC 20,{FBD6B0EB-0998-41C8-8281-2DF74B210199},0.900277,0.275507,13045911100,4149.583895,9111.00,0.396789,2773.954538,1926.070755,6991,1,6293.834842,0.593561,Low Income
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
940,ARC 20,{598AD0FB-AF93-4548-8636-800E766068F8},0.913901,0.134235,13223120204,3242.762370,1202.04,0.260394,1662.615257,857.091210,6385,1,5835.260017,0.507872,Not Low Income
942,ARC 20,{39429434-7228-49F6-A951-7DA25E80FD41},0.895824,0.020795,13223120303,1270.629835,1203.03,0.026200,46.818658,37.161278,1787,1,1600.837970,0.711041,Not Low Income
943,ARC 20,{71987763-5C58-49E8-9DAE-B5F3E2E7E2DA},0.929397,0.114799,13223120102,7620.260307,1201.02,0.160460,1808.542071,1293.902235,11271,1,10475.236037,0.676094,Not Low Income
945,ARC 20,{7CDED240-5D75-436B-BE4F-72E9E82FDD33},0.890380,0.173631,13223120302,5505.013546,1203.02,0.352241,4190.258936,2065.519935,11896,1,10591.961287,0.462762,Not Low Income
946,ARC 20,{36EAEB99-E656-4E24-97EC-2B747DA7D1BC},0.915706,0.228289,13223120202,5005.805781,1202.02,0.314849,2253.373996,1633.867000,7157,1,6553.704673,0.699428,Not Low Income

In [28]:
# Drop GeoID and GlobalID colmns
low_income_clean_df = low_income_df[{"Metro_Atlanta","Income_Level","LowAcces_LowIncome05miles","LowAccess_LowIncome1milePRCT","LowAccess_LowIncome05milesPRCT","POP2010","lapophalf","lapophalfshare","lapop1","lapop1share"}]
# low_income_clean_df
# Drop ARC 20
# low_income_clean_df.drop(low_income_clean_df.index[low_income_clean_df['Metro_Atlanta'] == 'Arc 20'], inplace = True)
low_income_clean_df = low_income_clean_df[low_income_clean_df.Metro_Atlanta != 'ARC 20']
# low_income_clean_df

# Round out all numbers 
# low_income_clean_df.round({'LowAcces_LowIncome.5miles': 1, 'lapop1': 0})
# low_income_clean_df.LowAcces_LowIncome05miles.apply(np.round)
low_income_clean_df.LowAcces_LowIncome05miles = low_income_clean_df.LowAcces_LowIncome05miles.round(2)
low_income_clean_df.lapop1 = low_income_clean_df.lapop1.round()
low_income_clean_df.lapophalf = low_income_clean_df.lapophalf.round()
low_income_clean_df.lapop1share = low_income_clean_df.lapop1share.round(3)
#low_income_clean_df.lapophalfshare = low_income_clean_df.lapophalfshare.round(3)
# # round %s
low_income_clean_df.LowAccess_LowIncome1milePRCT = low_income_clean_df.LowAccess_LowIncome1milePRCT.map("{:.2%}".format)
low_income_clean_df.LowAccess_LowIncome05milesPRCT = low_income_clean_df.LowAccess_LowIncome05milesPRCT.map("{:.2%}".format)
low_income_clean_df.lapophalfshare = low_income_clean_df.lapophalfshare.map("{:.2%}".format)
low_income_clean_df.lapop1share = low_income_clean_df.lapop1share.map("{:.2%}".format)
# # low_income_clean_df

# Change the % into % values
# low_income_clean_df_pct = low_income_clean_df/low_income_clean_df[low_income_clean_df.columns].sum()*100
# low_income_clean_df['percent'] = (low_income_clean_df['LowAccess_LowIncome05milesPRCT'] / low_income_clean_df['LowAccess_LowIncome05milesPRCT'].sum()) * 100
# low_income_clean_df.LowAccess_LowIncome1milePRCT = (low_income_clean_df.LowAccess_LowIncome1milePRCT * 100).astype(str) + '%'
# low_income_clean_df.LowAccess_LowIncome05milesPRCT = (low_income_clean_df.LowAccess_LowIncome05milesPRCT * 100).astype(str) + '%'
# low_income_clean_df.lapophalfshare = (low_income_clean_df.lapophalfshare * 100).astype(str) + '%'
# low_income_clean_df.lapop1share = (low_income_clean_df.lapop1share * 100).astype(str) + '%'
# low_income_clean_df

# Round all the percents
# low_income_clean_df.LowAccess_LowIncome1milePRCT = low_income_clean_df.LowAccess_LowIncome1milePRCT.round()
# low_income_clean_df.LowAccess_LowIncome05milesPRCT = low_income_clean_df.LowAccess_LowIncome05milesPRCT.round()
# low_income_clean_df.lapophalfshare = low_income_clean_df.lapophalfshare.round()
# low_income_clean_df.lapop1share = low_income_clean_df.lapop1share.round()
low_income_clean_df

,LowAccess_LowIncome05milesPRCT,lapophalfshare,Metro_Atlanta,lapop1,lapophalf,POP2010,LowAcces_LowIncome05miles,Income_Level,lapop1share,LowAccess_LowIncome1milePRCT
17,2.50%,85.67%,ARC 10,3105.0,4737.0,5530,138.04,Not Low Income,56.20%,1.48%
18,13.04%,84.75%,ARC 10,3252.0,6537.0,7713,1006.02,Not Low Income,42.20%,6.85%
19,11.58%,87.57%,ARC 10,1901.0,3984.0,4550,526.74,Not Low Income,41.80%,5.71%
20,15.85%,85.39%,ARC 10,3217.0,4916.0,5757,912.25,Not Low Income,55.90%,11.53%
22,12.72%,100.00%,ARC 10,3239.0,3239.0,3239,411.91,Not Low Income,100.00%,12.72%
...,...,...,...,...,...,...,...,...,...,...
904,15.79%,99.40%,ARC 10,6260.0,7076.0,7119,1124.20,Not Low Income,87.90%,13.49%
905,24.10%,74.13%,ARC 10,1914.0,6210.0,8376,2018.36,Not Low Income,22.80%,6.27%
907,17.93%,96.36%,ARC 10,5667.0,6919.0,7180,1287.42,Not Low Income,78.90%,15.07%
908,11.79%,97.98%,ARC 10,10628.0,11822.0,12065,1422.11,Not Low Income,88.10%,10.81%
910,16.93%,96.92%,ARC 10,10189.0,11199.0,11555,1956.13,Not Low Income,88.20%,15.23%

In [26]:
# # Drop GeoID and GlobalID colmns
# low_income_clean_df = low_income_df[{"Metro_Atlanta","Income_Level","LowAcces_LowIncome05miles","LowAccess_LowIncome1milePRCT","LowAccess_LowIncome05milesPRCT","POP2010","lapophalf","lapophalfshare","lapop1","lapop1share"}]
# # low_income_clean_df
# # Drop ARC 20
# # low_income_clean_df.drop(low_income_clean_df.index[low_income_clean_df['Metro_Atlanta'] == 'Arc 20'], inplace = True)
# low_income_clean_df = low_income_clean_df[low_income_clean_df.Metro_Atlanta != 'ARC 20']
# low_income_clean_df.LowAccess_LowIncome05milesPRCT = low_income_clean_df.LowAccess_LowIncome05milesPRCT.map("{:.2%}".format)
# low_income_clean_df.lapophalfshare = low_income_clean_df.lapophalfshare.map("{:.2%}".format)
# low_income_clean_df

In [10]:
stores_df = df[{"GEOID10","NAME10","Urban","PLNG_REGION","LILATracts_1And10","LILATracts_halfAnd10","LA1and10","LAhalfand10","LA1and20","LATracts_half","LATracts1","LATracts10","LATracts20","LowIncomeTracts","POP2010","lapophalf","lapophalfshare","lalowihalf","lalowihalfshare","lapop1","lapop1share","lalowi1","lalowi1share","OHU2010"}]
stores_df

,NAME10,LILATracts_1And10,lapop1,LA1and10,OHU2010,LAhalfand10,LowIncomeTracts,LA1and20,LATracts1,LILATracts_halfAnd10,...,lapophalfshare,lalowi1share,POP2010,lapophalf,Urban,lalowihalf,lalowihalfshare,LATracts10,GEOID10,PLNG_REGION
0,9101.03,0,4168.828564,0,1733,0,0,0,1,0,...,0.908377,0.165786,5020,4560.050754,0,928.643255,0.184989,0,13045910103,ARC 20
1,9101.04,0,8424.506346,1,3181,1,0,1,1,0,...,0.962295,0.292740,9273,8923.358003,1,2873.063683,0.309831,0,13045910104,ARC 20
2,9105.02,1,1979.496369,1,1001,1,1,1,1,1,...,0.994330,0.559638,2920,2903.442168,1,2388.115731,0.817848,0,13045910502,ARC 20
3,9108.00,0,3974.000026,0,1460,0,1,0,1,0,...,1.000000,0.391881,3974,3974.000026,0,1557.335152,0.391881,0,13045910800,ARC 20
4,9101.01,1,1464.668253,1,2262,1,1,1,1,1,...,0.762267,0.124557,5929,4519.483605,1,2164.547997,0.365078,0,13045910101,ARC 20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
943,1201.02,0,7620.260307,1,3477,1,0,1,1,0,...,0.929397,0.114799,11271,10475.236037,1,1808.542071,0.160460,0,13223120102,ARC 20
944,1201.03,0,6703.747686,0,2769,0,0,0,1,0,...,0.923887,0.139289,8567,7914.940175,0,1373.688844,0.160347,0,13223120103,ARC 20
945,1203.02,0,5505.013546,1,4503,1,0,1,1,0,...,0.890380,0.173631,11896,10591.961287,1,4190.258936,0.352241,0,13223120302,ARC 20
946,1202.02,0,5005.805781,1,2512,1,0,1,1,0,...,0.915706,0.228289,7157,6553.704673,1,2253.373996,0.314849,0,13223120202,ARC 20
947,1204.00,0,16900.097472,0,5872,0,1,0,1,0,...,1.000000,0.276499,17016,17015.999911,0,4737.150211,0.278394,0,13223120400,ARC 20