In [1]:
import csv
import os
import pandas as pd
import numpy as np

In [2]:
csvdata = '/Users/philliphenson/Desktop/project1/Food_Access_USDA.csv'
df = pd.read_csv(csvdata)
df.shape

(948, 46)

In [3]:
df.head(5)

,OBJECTID,GEOID10,NAME10,PLNG_REGION,LILATracts_1And10,LILATracts_halfAnd10,LILATracts_1And20,LILATracts_Vehicle,Urban,Rural,...,lapop1share,lalowi1,lalowi1share,lakids1,lakids1share,laseniors1,laseniors1share,lahunv1,lahunv1share,GlobalID
0,1,13045910103,9101.03,ARC 20,0,0,0,0,0,1,...,0.830444,832.244207,0.165786,1212.092423,0.812939,388.429152,0.868969,30.598599,0.017656,{5550A054-FDCE-4733-8B0C-A1947228CE5D}
1,2,13045910104,9101.04,ARC 20,0,0,0,0,1,0,...,0.908498,2714.580415,0.292740,2531.804935,0.935281,613.913957,0.769316,105.395259,0.033133,{C6FF347E-7A0E-49CC-95F8-6442CAB49326}
2,3,13045910502,9105.02,ARC 20,1,1,1,1,1,0,...,0.677910,1634.143695,0.559638,394.285953,0.595598,108.874610,0.513559,141.638535,0.141497,{59E4487C-A509-45FF-95E5-D3C0BBE650BB}
3,4,13045910800,9108.00,ARC 20,0,0,0,0,0,1,...,1.000000,1557.335152,0.391881,958.000006,1.000000,491.000002,1.000000,41.470898,0.028405,{B14B7E5F-B673-439E-9C6E-638AD0B38A33}
4,5,13045910101,9101.01,ARC 20,1,1,1,1,1,0,...,0.247035,738.495538,0.124557,400.600253,0.237182,153.517815,0.282722,61.471188,0.027176,{C3D7DA7F-5468-4F0E-A705-CA99B9E57806}

In [4]:
print(df.columns)

Index(['OBJECTID', 'GEOID10', 'NAME10', 'PLNG_REGION', 'LILATracts_1And10',
       'LILATracts_halfAnd10', 'LILATracts_1And20', 'LILATracts_Vehicle',
       'Urban', 'Rural', 'LA1and10', 'LAhalfand10', 'LA1and20',
       'LATracts_half', 'LATracts1', 'LATracts10', 'LATracts20', 'HUNVFlag',
       'GroupQuartersFlag', 'OHU2010', 'NUMGQTRS', 'PCTGQTRS',
       'LowIncomeTracts', 'POP2010', 'UATYP10', 'lapophalf', 'lapophalfshare',
       'lalowihalf', 'lalowihalfshare', 'lakidshalf', 'lakidshalfshare',
       'laseniorshalf', 'laseniorshalfshare', 'lahunvhalf', 'lahunvhalfshare',
       'lapop1', 'lapop1share', 'lalowi1', 'lalowi1share', 'lakids1',
       'lakids1share', 'laseniors1', 'laseniors1share', 'lahunv1',
       'lahunv1share', 'GlobalID'],
      dtype='object')

In [5]:
# Create three DF's to store different columns
kids_df = df[{"GEOID10","NAME10","PLNG_REGION","Urban","lakidshalf","lakidshalfshare","lakids1","lakids1share","GlobalID","lalowi1","lalowi1share","lapop1","lapop1share"}]
kids_df

,lakidshalfshare,lakids1share,lapop1share,lakids1,lapop1,Urban,lalowi1,GEOID10,GlobalID,lalowi1share,NAME10,PLNG_REGION,lakidshalf
0,0.892140,0.812939,0.830444,1212.092423,4168.828564,0,832.244207,13045910103,{5550A054-FDCE-4733-8B0C-A1947228CE5D},0.165786,9101.03,ARC 20,1330.181374
1,0.969294,0.935281,0.908498,2531.804935,8424.506346,1,2714.580415,13045910104,{C6FF347E-7A0E-49CC-95F8-6442CAB49326},0.292740,9101.04,ARC 20,2623.877557
2,0.992790,0.595598,0.677910,394.285953,1979.496369,1,1634.143695,13045910502,{59E4487C-A509-45FF-95E5-D3C0BBE650BB},0.559638,9105.02,ARC 20,657.226749
3,1.000000,1.000000,1.000000,958.000006,3974.000026,0,1557.335152,13045910800,{B14B7E5F-B673-439E-9C6E-638AD0B38A33},0.391881,9108.00,ARC 20,958.000006
4,0.744221,0.237182,0.247035,400.600253,1464.668253,1,738.495538,13045910101,{C3D7DA7F-5468-4F0E-A705-CA99B9E57806},0.124557,9101.01,ARC 20,1256.990076
...,...,...,...,...,...,...,...,...,...,...,...,...,...
943,0.931305,0.684471,0.676094,2519.536417,7620.260307,1,1293.902235,13223120102,{71987763-5C58-49E8-9DAE-B5F3E2E7E2DA},0.114799,1201.02,ARC 20,3428.134246
944,0.917964,0.762668,0.782508,2118.691044,6703.747686,0,1193.293010,13223120103,{CE73A80F-F658-48FD-91D0-A2B9D66ED1CC},0.139289,1201.03,ARC 20,2550.102779
945,0.886995,0.440785,0.462762,1449.743154,5505.013546,1,2065.519935,13223120302,{7CDED240-5D75-436B-BE4F-72E9E82FDD33},0.173631,1203.02,ARC 20,2917.327602
946,0.928530,0.737735,0.699428,1518.259609,5005.805781,1,1633.867000,13223120202,{36EAEB99-E656-4E24-97EC-2B747DA7D1BC},0.228289,1202.02,ARC 20,1910.915240
947,1.000000,0.993459,0.993189,5081.544245,16900.097472,0,4704.904817,13223120400,{A342945C-1EE3-47CE-974E-3EF37CF18862},0.276499,1204.00,ARC 20,5114.999969

In [6]:
# Low income vs non low income

low_income_df = df[{"GEOID10","NAME10","PLNG_REGION","Urban","LowIncomeTracts","lalowihalf","lalowihalfshare","lalowi1","lalowi1share","GlobalID","lapop1","POP2010","lapophalf","lapophalfshare","lapop1","lapop1share"}]
low_income_df

,LowIncomeTracts,lapophalfshare,lapop1share,lalowihalfshare,lapop1,lapophalf,Urban,lalowi1,POP2010,GEOID10,lalowihalf,GlobalID,lalowi1share,NAME10,PLNG_REGION
0,0,0.908377,0.830444,0.184989,4168.828564,4560.050754,0,832.244207,5020,13045910103,928.643255,{5550A054-FDCE-4733-8B0C-A1947228CE5D},0.165786,9101.03,ARC 20
1,0,0.962295,0.908498,0.309831,8424.506346,8923.358003,1,2714.580415,9273,13045910104,2873.063683,{C6FF347E-7A0E-49CC-95F8-6442CAB49326},0.292740,9101.04,ARC 20
2,1,0.994330,0.677910,0.817848,1979.496369,2903.442168,1,1634.143695,2920,13045910502,2388.115731,{59E4487C-A509-45FF-95E5-D3C0BBE650BB},0.559638,9105.02,ARC 20
3,1,1.000000,1.000000,0.391881,3974.000026,3974.000026,0,1557.335152,3974,13045910800,1557.335152,{B14B7E5F-B673-439E-9C6E-638AD0B38A33},0.391881,9108.00,ARC 20
4,1,0.762267,0.247035,0.365078,1464.668253,4519.483605,1,738.495538,5929,13045910101,2164.547997,{C3D7DA7F-5468-4F0E-A705-CA99B9E57806},0.124557,9101.01,ARC 20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
943,0,0.929397,0.676094,0.160460,7620.260307,10475.236037,1,1293.902235,11271,13223120102,1808.542071,{71987763-5C58-49E8-9DAE-B5F3E2E7E2DA},0.114799,1201.02,ARC 20
944,0,0.923887,0.782508,0.160347,6703.747686,7914.940175,0,1193.293010,8567,13223120103,1373.688844,{CE73A80F-F658-48FD-91D0-A2B9D66ED1CC},0.139289,1201.03,ARC 20
945,0,0.890380,0.462762,0.352241,5505.013546,10591.961287,1,2065.519935,11896,13223120302,4190.258936,{7CDED240-5D75-436B-BE4F-72E9E82FDD33},0.173631,1203.02,ARC 20
946,0,0.915706,0.699428,0.314849,5005.805781,6553.704673,1,1633.867000,7157,13223120202,2253.373996,{36EAEB99-E656-4E24-97EC-2B747DA7D1BC},0.228289,1202.02,ARC 20
947,1,1.000000,0.993189,0.278394,16900.097472,17015.999911,0,4704.904817,17016,13223120400,4737.150211,{A342945C-1EE3-47CE-974E-3EF37CF18862},0.276499,1204.00,ARC 20

In [7]:
# Rename columns
low_income_df=low_income_df.rename(columns={"PLNG_REGION": "Metro_Atlanta", "GlobalID": "Global_ID","LowIncomeTracts": "Income_Level", "lalowihalf": "LowAcces_LowIncome05miles", "lalowi1share": "LowAccess_LowIncome1milePRCT", "lalowihalfshare": "LowAccess_LowIncome05milesPRCT", "lalowi1": "LowAccess_LowIncome1mile", "GEOID10": "Geo_ID", "NAME10": "Name"})
low_income_df

,Income_Level,lapophalfshare,lapop1share,LowAccess_LowIncome05milesPRCT,lapop1,lapophalf,Urban,LowAccess_LowIncome1mile,POP2010,Geo_ID,LowAcces_LowIncome05miles,Global_ID,LowAccess_LowIncome1milePRCT,Name,Metro_Atlanta
0,0,0.908377,0.830444,0.184989,4168.828564,4560.050754,0,832.244207,5020,13045910103,928.643255,{5550A054-FDCE-4733-8B0C-A1947228CE5D},0.165786,9101.03,ARC 20
1,0,0.962295,0.908498,0.309831,8424.506346,8923.358003,1,2714.580415,9273,13045910104,2873.063683,{C6FF347E-7A0E-49CC-95F8-6442CAB49326},0.292740,9101.04,ARC 20
2,1,0.994330,0.677910,0.817848,1979.496369,2903.442168,1,1634.143695,2920,13045910502,2388.115731,{59E4487C-A509-45FF-95E5-D3C0BBE650BB},0.559638,9105.02,ARC 20
3,1,1.000000,1.000000,0.391881,3974.000026,3974.000026,0,1557.335152,3974,13045910800,1557.335152,{B14B7E5F-B673-439E-9C6E-638AD0B38A33},0.391881,9108.00,ARC 20
4,1,0.762267,0.247035,0.365078,1464.668253,4519.483605,1,738.495538,5929,13045910101,2164.547997,{C3D7DA7F-5468-4F0E-A705-CA99B9E57806},0.124557,9101.01,ARC 20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
943,0,0.929397,0.676094,0.160460,7620.260307,10475.236037,1,1293.902235,11271,13223120102,1808.542071,{71987763-5C58-49E8-9DAE-B5F3E2E7E2DA},0.114799,1201.02,ARC 20
944,0,0.923887,0.782508,0.160347,6703.747686,7914.940175,0,1193.293010,8567,13223120103,1373.688844,{CE73A80F-F658-48FD-91D0-A2B9D66ED1CC},0.139289,1201.03,ARC 20
945,0,0.890380,0.462762,0.352241,5505.013546,10591.961287,1,2065.519935,11896,13223120302,4190.258936,{7CDED240-5D75-436B-BE4F-72E9E82FDD33},0.173631,1203.02,ARC 20
946,0,0.915706,0.699428,0.314849,5005.805781,6553.704673,1,1633.867000,7157,13223120202,2253.373996,{36EAEB99-E656-4E24-97EC-2B747DA7D1BC},0.228289,1202.02,ARC 20
947,1,1.000000,0.993189,0.278394,16900.097472,17015.999911,0,4704.904817,17016,13223120400,4737.150211,{A342945C-1EE3-47CE-974E-3EF37CF18862},0.276499,1204.00,ARC 20

In [8]:
# Drop stuff from dataframe
# This drops all 0 values from "Urban"
low_income_df = low_income_df[low_income_df.Urban != 0]
low_income_df
# Change values in dataframe
# for col in low_income_df.columns():
# low_income_df.loc[low_income_df["Income_Level"] == '0', "Income_Level"] = "Not Low Income"
# low_income_df.loc[low_income_df["Income_Level"] == '1', "Income_Level"] = "Low Income" 

# low_income_df.Income_Level = low_income_df.Income_Level.map({ 0 : "Not Low Income", 1 : "Low Income"})

low_income_df.replace({'Income_Level':{0:"Not Low Income",1:"Low Income"}},inplace=True)
low_income_df

/Users/philliphenson/opt/anaconda3/envs/PythonData/lib/python3.6/site-packages/pandas/core/indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

,Income_Level,lapophalfshare,lapop1share,LowAccess_LowIncome05milesPRCT,lapop1,lapophalf,Urban,LowAccess_LowIncome1mile,POP2010,Geo_ID,LowAcces_LowIncome05miles,Global_ID,LowAccess_LowIncome1milePRCT,Name,Metro_Atlanta
1,Not Low Income,0.962295,0.908498,0.309831,8424.506346,8923.358003,1,2714.580415,9273,13045910104,2873.063683,{C6FF347E-7A0E-49CC-95F8-6442CAB49326},0.292740,9101.04,ARC 20
2,Low Income,0.994330,0.677910,0.817848,1979.496369,2903.442168,1,1634.143695,2920,13045910502,2388.115731,{59E4487C-A509-45FF-95E5-D3C0BBE650BB},0.559638,9105.02,ARC 20
4,Low Income,0.762267,0.247035,0.365078,1464.668253,4519.483605,1,738.495538,5929,13045910101,2164.547997,{C3D7DA7F-5468-4F0E-A705-CA99B9E57806},0.124557,9101.01,ARC 20
5,Not Low Income,0.943188,0.796952,0.296743,9346.658357,11061.713867,1,2933.637950,11728,13045910200,3480.197243,{68A7D1D7-2258-4893-A214-168B6A59D4C3},0.250140,9102.00,ARC 20
8,Low Income,0.900277,0.593561,0.396789,4149.583895,6293.834842,1,1926.070755,6991,13045911100,2773.954538,{FBD6B0EB-0998-41C8-8281-2DF74B210199},0.275507,9111.00,ARC 20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
940,Not Low Income,0.913901,0.507872,0.260394,3242.762370,5835.260017,1,857.091210,6385,13223120204,1662.615257,{598AD0FB-AF93-4548-8636-800E766068F8},0.134235,1202.04,ARC 20
942,Not Low Income,0.895824,0.711041,0.026200,1270.629835,1600.837970,1,37.161278,1787,13223120303,46.818658,{39429434-7228-49F6-A951-7DA25E80FD41},0.020795,1203.03,ARC 20
943,Not Low Income,0.929397,0.676094,0.160460,7620.260307,10475.236037,1,1293.902235,11271,13223120102,1808.542071,{71987763-5C58-49E8-9DAE-B5F3E2E7E2DA},0.114799,1201.02,ARC 20
945,Not Low Income,0.890380,0.462762,0.352241,5505.013546,10591.961287,1,2065.519935,11896,13223120302,4190.258936,{7CDED240-5D75-436B-BE4F-72E9E82FDD33},0.173631,1203.02,ARC 20
946,Not Low Income,0.915706,0.699428,0.314849,5005.805781,6553.704673,1,1633.867000,7157,13223120202,2253.373996,{36EAEB99-E656-4E24-97EC-2B747DA7D1BC},0.228289,1202.02,ARC 20

In [15]:
# Drop GeoID and GlobalID colmns
low_income_clean_df = low_income_df[{"Metro_Atlanta","Income_Level","LowAcces_LowIncome05miles","LowAccess_LowIncome1milePRCT","LowAccess_LowIncome05milesPRCT","POP2010","lapophalf","lapophalfshare","lapop1","lapop1share"}]
# low_income_clean_df
# Drop ARC 20
# low_income_clean_df.drop(low_income_clean_df.index[low_income_clean_df['Metro_Atlanta'] == 'Arc 20'], inplace = True)
low_income_clean_df = low_income_clean_df[low_income_clean_df.Metro_Atlanta != 'ARC 20']
# low_income_clean_df

# Round out all numbers 
# low_income_clean_df.round({'LowAcces_LowIncome.5miles': 1, 'lapop1': 0})
# low_income_clean_df.LowAcces_LowIncome05miles.apply(np.round)
low_income_clean_df.LowAcces_LowIncome05miles = low_income_clean_df.LowAcces_LowIncome05miles.round()
low_income_clean_df.lapop1 = low_income_clean_df.lapop1.round()
low_income_clean_df.lapophalf = low_income_clean_df.lapophalf.round()
low_income_clean_df.lapop1share = low_income_clean_df.lapop1share.round(3)
low_income_clean_df.lapophalfshare = low_income_clean_df.lapophalfshare.round(3)
# low_income_clean_df

# Change the % into % values
# low_income_clean_df_pct = low_income_clean_df/low_income_clean_df[low_income_clean_df.columns].sum()*100
# low_income_clean_df['percent'] = (low_income_clean_df['LowAccess_LowIncome05milesPRCT'] / low_income_clean_df['LowAccess_LowIncome05milesPRCT'].sum()) * 100
low_income_clean_df.LowAccess_LowIncome1milePRCT = (low_income_clean_df.LowAccess_LowIncome1milePRCT * 100).astype(str) + '%'
low_income_clean_df.LowAccess_LowIncome05milesPRCT = (low_income_clean_df.LowAccess_LowIncome05milesPRCT * 100).astype(str) + '%'
low_income_clean_df.lapophalfshare = (low_income_clean_df.lapophalfshare * 100).astype(str) + '%'
low_income_clean_df.lapop1share = (low_income_clean_df.lapop1share * 100).astype(str) + '%'
low_income_clean_df

,lapophalfshare,lapop1share,LowAccess_LowIncome05milesPRCT,lapop1,lapophalf,LowAcces_LowIncome05miles,Income_Level,POP2010,LowAccess_LowIncome1milePRCT,Metro_Atlanta
17,85.7%,56.2%,2.496166%,3105.0,4737.0,138.0,Not Low Income,5530,1.480552%,ARC 10
18,84.7%,42.199999999999996%,13.043232%,3252.0,6537.0,1006.0,Not Low Income,7713,6.84622%,ARC 10
19,87.6%,41.8%,11.576703%,1901.0,3984.0,527.0,Not Low Income,4550,5.71026%,ARC 10
20,85.39999999999999%,55.900000000000006%,15.845877999999999%,3217.0,4916.0,912.0,Not Low Income,5757,11.531471%,ARC 10
22,100.0%,100.0%,12.717227000000001%,3239.0,3239.0,412.0,Not Low Income,3239,12.717227000000001%,ARC 10
...,...,...,...,...,...,...,...,...,...,...
904,99.4%,87.9%,15.791485%,6260.0,7076.0,1124.0,Not Low Income,7119,13.486170000000003%,ARC 10
905,74.1%,22.8%,24.096999%,1914.0,6210.0,2018.0,Not Low Income,8376,6.272452%,ARC 10
907,96.39999999999999%,78.9%,17.930644%,5667.0,6919.0,1287.0,Not Low Income,7180,15.074319%,ARC 10
908,98.0%,88.1%,11.787037999999999%,10628.0,11822.0,1422.0,Not Low Income,12065,10.806668%,ARC 10
910,96.89999999999999%,88.2%,16.928900000000002%,10189.0,11199.0,1956.0,Not Low Income,11555,15.229337000000001%,ARC 10

In [10]:
stores_df = df[{"GEOID10","NAME10","Urban","PLNG_REGION","LILATracts_1And10","LILATracts_halfAnd10","LA1and10","LAhalfand10","LA1and20","LATracts_half","LATracts1","LATracts10","LATracts20","LowIncomeTracts","POP2010","lapophalf","lapophalfshare","lalowihalf","lalowihalfshare","lapop1","lapop1share","lalowi1","lalowi1share","OHU2010"}]
stores_df

,NAME10,LILATracts_1And10,lapop1,LA1and10,OHU2010,LAhalfand10,LowIncomeTracts,LA1and20,LATracts1,LILATracts_halfAnd10,...,lapophalfshare,lalowi1share,POP2010,lapophalf,Urban,lalowihalf,lalowihalfshare,LATracts10,GEOID10,PLNG_REGION
0,9101.03,0,4168.828564,0,1733,0,0,0,1,0,...,0.908377,0.165786,5020,4560.050754,0,928.643255,0.184989,0,13045910103,ARC 20
1,9101.04,0,8424.506346,1,3181,1,0,1,1,0,...,0.962295,0.292740,9273,8923.358003,1,2873.063683,0.309831,0,13045910104,ARC 20
2,9105.02,1,1979.496369,1,1001,1,1,1,1,1,...,0.994330,0.559638,2920,2903.442168,1,2388.115731,0.817848,0,13045910502,ARC 20
3,9108.00,0,3974.000026,0,1460,0,1,0,1,0,...,1.000000,0.391881,3974,3974.000026,0,1557.335152,0.391881,0,13045910800,ARC 20
4,9101.01,1,1464.668253,1,2262,1,1,1,1,1,...,0.762267,0.124557,5929,4519.483605,1,2164.547997,0.365078,0,13045910101,ARC 20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
943,1201.02,0,7620.260307,1,3477,1,0,1,1,0,...,0.929397,0.114799,11271,10475.236037,1,1808.542071,0.160460,0,13223120102,ARC 20
944,1201.03,0,6703.747686,0,2769,0,0,0,1,0,...,0.923887,0.139289,8567,7914.940175,0,1373.688844,0.160347,0,13223120103,ARC 20
945,1203.02,0,5505.013546,1,4503,1,0,1,1,0,...,0.890380,0.173631,11896,10591.961287,1,4190.258936,0.352241,0,13223120302,ARC 20
946,1202.02,0,5005.805781,1,2512,1,0,1,1,0,...,0.915706,0.228289,7157,6553.704673,1,2253.373996,0.314849,0,13223120202,ARC 20
947,1204.00,0,16900.097472,0,5872,0,1,0,1,0,...,1.000000,0.276499,17016,17015.999911,0,4737.150211,0.278394,0,13223120400,ARC 20